"""Public access to metadata from the vendored OpenAL XML registry."""

from pyalsoft._generated.registry import (
    API_SETS,
    COMMANDS,
    DEFINES,
    ENUMS,
    REGISTRY_COMMENTS,
    REGISTRY_NOTES,
    REGISTRY_SHA256,
    TYPES,
    UPSTREAM_COMMIT,
    UPSTREAM_VERSION,
)
from pyalsoft._generated.semantics import (
    COMMAND_WRAPPERS,
    COMMAND_WRAPPERS_BY_NAME,
    ENUM_GROUPS,
    ENUM_GROUPS_BY_NAME,
    OBJECT_PROPERTIES,
    OBJECT_PROPERTIES_BY_KEY,
)
from pyalsoft._specs import (
    ApiMemberSpec,
    ApiSetSpec,
    CommandSpec,
    CommandWrapperSpec,
    DefineSpec,
    EnumGroupSpec,
    EnumSpec,
    ObjectPropertySpec,
    ParameterSpec,
    PropertySpec,
    RegistryNoteSpec,
    RequirementSpec,
    TypeSpec,
    WrapperParameterSpec,
)

__all__ = [
    "API_SETS",
    "COMMANDS",
    "COMMAND_WRAPPERS",
    "COMMAND_WRAPPERS_BY_NAME",
    "DEFINES",
    "ENUMS",
    "ENUM_GROUPS",
    "ENUM_GROUPS_BY_NAME",
    "OBJECT_PROPERTIES",
    "OBJECT_PROPERTIES_BY_KEY",
    "REGISTRY_COMMENTS",
    "REGISTRY_NOTES",
    "REGISTRY_SHA256",
    "TYPES",
    "UPSTREAM_COMMIT",
    "UPSTREAM_VERSION",
    "ApiMemberSpec",
    "ApiSetSpec",
    "CommandSpec",
    "CommandWrapperSpec",
    "DefineSpec",
    "EnumSpec",
    "EnumGroupSpec",
    "ObjectPropertySpec",
    "ParameterSpec",
    "PropertySpec",
    "RegistryNoteSpec",
    "RequirementSpec",
    "TypeSpec",
    "WrapperParameterSpec",
]
