# Generated by tools/generate_bindings.py. Do not edit by hand.
# OpenAL Soft 1.25.2: b2c48f7718ef3fcf67921a8b6534c4914e328970
# Source: https://raw.githubusercontent.com/kcat/openal-soft/1.25.2/registry/xml/al.xml
# Registry SHA-256: f4a5eb2f94adbb80e8afb1c510d2993932eb74519568c28f3e4919864acddf4a
# Registry notice: LICENSES/OpenAL-Registry.txt

from __future__ import annotations

import ctypes as _ctypes

ALboolean = _ctypes.c_char
ALchar = _ctypes.c_char
ALbyte = _ctypes.c_byte
ALubyte = _ctypes.c_ubyte
ALshort = _ctypes.c_short
ALushort = _ctypes.c_ushort
ALint = _ctypes.c_int
ALuint = _ctypes.c_uint
ALsizei = _ctypes.c_int
ALenum = _ctypes.c_int
ALfloat = _ctypes.c_float
ALdouble = _ctypes.c_double
ALvoid = None

class _GUID(_ctypes.Structure):
    """Opaque C structure ``_GUID``."""

    pass

ALint64SOFT = _ctypes.c_int64
ALuint64SOFT = _ctypes.c_uint64

class ALCdevice(_ctypes.Structure):
    """Opaque C structure ``ALCdevice``."""

    pass

class ALCcontext(_ctypes.Structure):
    """Opaque C structure ``ALCcontext``."""

    pass

ALCboolean = _ctypes.c_char
ALCchar = _ctypes.c_char
ALCbyte = _ctypes.c_byte
ALCubyte = _ctypes.c_ubyte
ALCshort = _ctypes.c_short
ALCushort = _ctypes.c_ushort
ALCint = _ctypes.c_int
ALCuint = _ctypes.c_uint
ALCsizei = _ctypes.c_int
ALCenum = _ctypes.c_int
ALCfloat = _ctypes.c_float
ALCdouble = _ctypes.c_double
ALCvoid = None
ALCint64SOFT = _ctypes.c_int64
ALCuint64SOFT = _ctypes.c_uint64

LPALFOLDBACKCALLBACK = _ctypes.CFUNCTYPE(None, ALenum, ALsizei)
ALEVENTPROCSOFT = _ctypes.CFUNCTYPE(None, ALenum, ALuint, ALuint, ALsizei, _ctypes.c_char_p, _ctypes.c_void_p)
ALBUFFERCALLBACKTYPESOFT = _ctypes.CFUNCTYPE(ALsizei, _ctypes.c_void_p, _ctypes.c_void_p, ALsizei)
ALDEBUGPROCEXT = _ctypes.CFUNCTYPE(None, ALenum, ALenum, ALuint, ALenum, ALsizei, _ctypes.c_char_p, _ctypes.c_void_p)
ALCEVENTPROCTYPESOFT = _ctypes.CFUNCTYPE(None, ALCenum, ALCenum, _ctypes.POINTER(ALCdevice), ALCsizei, _ctypes.c_char_p, _ctypes.c_void_p)

__all__ = (
    'ALboolean',
    'ALchar',
    'ALbyte',
    'ALubyte',
    'ALshort',
    'ALushort',
    'ALint',
    'ALuint',
    'ALsizei',
    'ALenum',
    'ALfloat',
    'ALdouble',
    'ALvoid',
    '_GUID',
    'ALint64SOFT',
    'ALuint64SOFT',
    'LPALFOLDBACKCALLBACK',
    'ALEVENTPROCSOFT',
    'ALBUFFERCALLBACKTYPESOFT',
    'ALDEBUGPROCEXT',
    'ALCdevice',
    'ALCcontext',
    'ALCboolean',
    'ALCchar',
    'ALCbyte',
    'ALCubyte',
    'ALCshort',
    'ALCushort',
    'ALCint',
    'ALCuint',
    'ALCsizei',
    'ALCenum',
    'ALCfloat',
    'ALCdouble',
    'ALCvoid',
    'ALCint64SOFT',
    'ALCuint64SOFT',
    'ALCEVENTPROCTYPESOFT',
)
