"""Shared rendering helpers."""

from __future__ import annotations

from .models import SourceInfo


def _generated_header(source: SourceInfo, digest: str) -> list[str]:
    return [
        "# Generated by tools/generate_bindings.py. Do not edit by hand.",
        f"# OpenAL Soft {source.version}: {source.commit}",
        f"# Source: {source.source_url}",
        f"# Registry SHA-256: {digest}",
        "# Registry notice: LICENSES/OpenAL-Registry.txt",
        "",
        "from __future__ import annotations",
        "",
    ]
