"""Render human and machine-readable registry documentation."""

from __future__ import annotations

from .c_types import _ctypes_base_expressions, _resolve_constants, _resolve_defines
from .common import _generated_header
from .models import (
    ParameterDecl,
    PropertyDecl,
    Registry,
    RequirementDecl,
    SemanticOverrides,
    SourceInfo,
)
from .render_api import (
    _group_python_names,
    _wrapper_method_parameters,
    _wrapper_return_annotation,
)
from .semantics import (
    build_command_wrappers,
    build_effective_properties,
    build_enum_groups,
)


def _markdown(value: str | None) -> str:
    if value is None:
        return "n/a"
    return value.replace("|", "\\|").replace("\n", " ")


def render_documentation(
    registry: Registry,
    source: SourceInfo,
    digest: str,
    overrides: SemanticOverrides,
) -> str:
    """Render a human-readable reference from the same semantic model as code."""

    groups = build_enum_groups(registry, overrides)
    properties = build_effective_properties(registry, overrides)
    wrappers = build_command_wrappers(registry, overrides)
    known_types = _ctypes_base_expressions(registry, alias_prefix="")
    group_names = _group_python_names(registry, overrides)
    callbacks = {item.name for item in registry.types if item.category == "funcpointer"}
    lines = [
        "<!-- Generated by tools/generate_bindings.py. Do not edit by hand. -->",
        "",
        "# PyALSoft bindings API reference",
        "",
        f"Registry: OpenAL Soft {source.version} (`{source.commit}`)",
        "",
        f"Registry SHA-256: `{digest}`",
        "",
        "The supported low-level interface lives in `pyalsoft.bindings`. Its "
        "`OpenALLibrary.al*` and `OpenALLibrary.alc*` attributes remain raw "
        "`ctypes` functions. The `library.al` and `library.alc` namespaces "
        "below accept Python values, infer input array lengths, allocate output "
        "parameters, and return normal Python values.",
        "Extensions are exposed as generated capability objects. For example, "
        "`library.extensions.alc_ext_efx` lists its commands, enums, types, and "
        "dependencies; `is_present(device)` checks runtime availability.",
        "Owned playback, capture, loopback, and context handles are documented "
        "in `docs/backend.md`.",
        "",
        "Semantic corrections that cannot be represented by the upstream XML "
        "are reviewed in `tools/semantic_overrides.toml`.",
        "",
        "## Object properties",
        "",
    ]
    for object_name in dict.fromkeys(item.object_name for item in properties):
        lines.extend(
            [
                f"### {object_name.title()}",
                "",
                "| Python property | OpenAL selector | Type | Access | Range | Default | Extension | Generated |",
                "| --- | --- | --- | --- | --- | --- | --- | --- |",
            ]
        )
        for property_ in properties:
            if property_.object_name != object_name:
                continue
            access = "read/write" if property_.writable else "read-only"
            extension = ", ".join(property_.extensions) or "core"
            generated = "yes" if property_.getter is not None else "schema only"
            lines.append(
                f"| `{property_.python_name}` | `{property_.enum_name}` | "
                f"`{' / '.join(property_.value_types) or 'unspecified'}` | "
                f"{access} | {_markdown(property_.range)} | "
                f"{_markdown(property_.default)} | {_markdown(extension)} | "
                f"{generated} |"
            )
        lines.append("")

    lines.extend(["## Python command namespaces", ""])
    for namespace in ("AL", "ALC"):
        lines.extend(
            [
                f"### `library.{namespace.lower()}`",
                "",
                "| Python signature | C command | Availability | Description |",
                "| --- | --- | --- | --- |",
            ]
        )
        for wrapper in wrappers:
            if wrapper.namespace != namespace:
                continue
            parameters = ", ".join(
                _wrapper_method_parameters(wrapper, known_types, group_names, callbacks)
            )
            result = _wrapper_return_annotation(
                wrapper, known_types, group_names, callbacks
            )
            availability = wrapper.extension or "core"
            lines.append(
                f"| `{wrapper.python_name}({parameters}) -> {result}` | "
                f"`{wrapper.name}` | `{availability}` | "
                f"{_markdown(wrapper.comment)} |"
            )
            if wrapper.string_list_name is not None:
                lines.append(
                    f"| `{wrapper.string_list_name}({parameters}) -> tuple[str, ...]` | "
                    f"`{wrapper.name}` | `{availability}` | "
                    "Return a NUL-separated string list. |"
                )
        lines.append("")

    lines.extend(["## Enum groups", ""])
    for namespace, group, python_name, members, bitmask in groups:
        base = "IntFlag" if bitmask else "IntEnum"
        rendered_members = ", ".join(f"`{item}`" for item in members)
        lines.extend(
            [
                f"### `{python_name}`",
                "",
                f"Registry group `{namespace}:{group}` generated as `{base}`.",
                "",
                rendered_members,
                "",
            ]
        )

    lines.extend(
        [
            "## Extensions",
            "",
            "| Extension | APIs | Dependencies | Commands | Enums |",
            "| --- | --- | --- | ---: | ---: |",
        ]
    )
    for api_set in registry.api_sets:
        if api_set.kind != "extension":
            continue
        dependencies = tuple(
            dict.fromkeys(
                requirement.depends
                for requirement in api_set.requirements
                if requirement.depends is not None
            )
        )
        command_count = sum(
            member.kind == "command"
            for requirement in api_set.requirements
            for member in requirement.members
        )
        enum_count = sum(
            member.kind == "enum"
            for requirement in api_set.requirements
            for member in requirement.members
        )
        lines.append(
            f"| `{api_set.name}` | `{', '.join(api_set.apis)}` | "
            f"{_markdown(', '.join(dependencies) or None)} | "
            f"{command_count} | {enum_count} |"
        )
    lines.append("")
    return "\n".join(lines)


def _render_parameter(parameter: ParameterDecl) -> str:
    return (
        "ParameterSpec("
        f"{parameter.name!r}, {parameter.c_type!r}, {parameter.length!r}, "
        f"{parameter.group!r}, {parameter.object_class!r})"
    )


def _render_property(property_: PropertyDecl) -> str:
    return (
        "PropertySpec("
        f"{property_.objects!r}, {property_.value_types!r}, {property_.range!r}, "
        f"{property_.default!r}, {property_.groups!r}, "
        f"{property_.object_class!r}, {property_.kind!r})"
    )


def _render_requirement(requirement: RequirementDecl) -> str:
    members = ", ".join(
        f"ApiMemberSpec({member.kind!r}, {member.name!r})"
        for member in requirement.members
    )
    members = f"({members},)" if members else "()"
    return (
        f"RequirementSpec({requirement.api!r}, {requirement.comment!r}, "
        f"{members}, {requirement.depends!r})"
    )


def render_registry_metadata(
    registry: Registry, source: SourceInfo, digest: str
) -> str:
    """Render language-neutral metadata alongside the ctypes binding layer."""

    enum_values = _resolve_constants(registry.enums)
    define_values = _resolve_defines(registry.defines, enum_values)
    lines = _generated_header(source, digest)
    lines.extend(
        [
            "from pyalsoft.bindings._specs import (",
            "    ApiMemberSpec,",
            "    ApiSetSpec,",
            "    CommandSpec,",
            "    DefineSpec,",
            "    EnumSpec,",
            "    ParameterSpec,",
            "    PropertySpec,",
            "    RegistryNoteSpec,",
            "    RequirementSpec,",
            "    TypeSpec,",
            ")",
            "",
            f"UPSTREAM_VERSION = {source.version!r}",
            f"UPSTREAM_COMMIT = {source.commit!r}",
            f"REGISTRY_SHA256 = {digest!r}",
            f"REGISTRY_COMMENTS = {registry.comments!r}",
            "REGISTRY_NOTES: tuple[RegistryNoteSpec, ...] = (",
        ]
    )
    lines.extend(
        f"    RegistryNoteSpec({item.parent!r}, {item.subject!r}, {item.text!r}),"
        for item in registry.notes
    )
    lines.extend(
        [
            ")",
            "",
            "TYPES: tuple[TypeSpec, ...] = (",
        ]
    )
    lines.extend(
        "    TypeSpec("
        f"{item.namespace!r}, {item.name!r}, {item.category!r}, "
        f"{item.declaration!r}, {item.comment!r}),"
        for item in registry.types
    )
    lines.extend([")", "", "DEFINES: tuple[DefineSpec, ...] = ("])
    for define in registry.defines:
        value = define_values[define.name]
        python_value = value.literal if value is not None else "None"
        lines.append(
            "    DefineSpec("
            f"{define.namespace!r}, {define.name!r}, {define.replacement!r}, "
            f"{python_value}),"
        )
    lines.extend([")", "", "ENUMS: tuple[EnumSpec, ...] = ("])
    for enum in registry.enums:
        properties = ", ".join(
            _render_property(property_) for property_ in enum.properties
        )
        properties = f"({properties},)" if properties else "()"
        lines.append(
            "    EnumSpec("
            f"{enum.namespace!r}, {enum.name!r}, {enum.value!r}, "
            f"{enum.groups!r}, {enum.deprecated!r}, {enum.block_group!r}, "
            f"{enum.comment!r}, {enum.comments!r}, {properties}),"
        )
    lines.extend([")", "", "COMMANDS: tuple[CommandSpec, ...] = ("])
    for command in registry.commands:
        parameters = ", ".join(
            _render_parameter(parameter) for parameter in command.parameters
        )
        parameters = f"({parameters},)" if parameters else "()"
        lines.append(
            "    CommandSpec("
            f"{command.namespace!r}, {command.name!r}, {command.return_type!r}, "
            f"{parameters}, {command.export!r}, {command.function_pointer!r}, "
            f"{command.deprecated!r}, {command.return_group!r}, "
            f"{command.comment!r}, {command.comments!r}, "
            f"{command.command_attribute!r}),"
        )
    lines.extend([")", "", "API_SETS: tuple[ApiSetSpec, ...] = ("])
    for api_set in registry.api_sets:
        requirements = ", ".join(
            _render_requirement(requirement) for requirement in api_set.requirements
        )
        requirements = f"({requirements},)" if requirements else "()"
        lines.append(
            "    ApiSetSpec("
            f"{api_set.kind!r}, {api_set.name!r}, {api_set.apis!r}, "
            f"{api_set.number!r}, {api_set.annex!r}, {requirements}, "
            f"{api_set.comments!r}),"
        )
    lines.extend([")", ""])
    return "\n".join(lines)
