"""Explicit managed playback sessions and resource operations."""

from pyalsoft._managed.playback.session import (
    Playback,
    close_playback,
    get_playback_config,
    get_playback_info,
    list_hrtf_profiles,
    list_playback_devices,
    open_playback,
    reconfigure_playback,
)
from pyalsoft._managed.playback.source_controls import list_resamplers
from pyalsoft._managed.playback.streams import (
    finish_stream,
    open_stream,
    start_stream,
    try_write_stream,
    update_stream,
)
from pyalsoft._managed.playback.voices import (
    get_playback_clock,
    get_voice_clock,
    get_voice_latency,
    get_voice_status,
    pause,
    release,
    release_finished,
    restart,
    resume,
    rewind,
    seek,
    seek_frames,
    set_voice_config,
    stop,
    upload,
)

__all__ = [
    "Playback",
    "close_playback",
    "finish_stream",
    "get_playback_config",
    "get_playback_info",
    "get_playback_clock",
    "get_voice_clock",
    "get_voice_latency",
    "get_voice_status",
    "list_hrtf_profiles",
    "list_playback_devices",
    "list_resamplers",
    "open_playback",
    "open_stream",
    "pause",
    "release",
    "release_finished",
    "reconfigure_playback",
    "restart",
    "resume",
    "rewind",
    "seek",
    "seek_frames",
    "set_voice_config",
    "start_stream",
    "stop",
    "try_write_stream",
    "update_stream",
    "upload",
]
