# Generated by tools/generate_bindings.py. Do not edit by hand.
# OpenAL Soft 1.25.2: b2c48f7718ef3fcf67921a8b6534c4914e328970
# Source: https://raw.githubusercontent.com/kcat/openal-soft/1.25.2/registry/xml/al.xml
# Registry SHA-256: f4a5eb2f94adbb80e8afb1c510d2993932eb74519568c28f3e4919864acddf4a
# Registry notice: LICENSES/OpenAL-Registry.txt

from __future__ import annotations

from pyalsoft.bindings import _extensions


class ExtensionCapabilities(_extensions.ExtensionNamespace):
    """Capabilities for every extension declared by the registry."""

    @property
    def al_loki_ima_adpcm_format(self) -> _extensions.Extension:
        """Return capabilities for ``AL_LOKI_IMA_ADPCM_format``."""

        return self._get('AL_LOKI_IMA_ADPCM_format')

    @property
    def al_loki_wave_format(self) -> _extensions.Extension:
        """Return capabilities for ``AL_LOKI_WAVE_format``."""

        return self._get('AL_LOKI_WAVE_format')

    @property
    def al_ext_vorbis(self) -> _extensions.Extension:
        """Return capabilities for ``AL_EXT_vorbis``."""

        return self._get('AL_EXT_vorbis')

    @property
    def al_loki_quadriphonic(self) -> _extensions.Extension:
        """Return capabilities for ``AL_LOKI_quadriphonic``."""

        return self._get('AL_LOKI_quadriphonic')

    @property
    def al_ext_float32(self) -> _extensions.Extension:
        """Return capabilities for ``AL_EXT_float32``."""

        return self._get('AL_EXT_float32')

    @property
    def al_ext_double(self) -> _extensions.Extension:
        """Return capabilities for ``AL_EXT_double``."""

        return self._get('AL_EXT_double')

    @property
    def al_ext_mulaw(self) -> _extensions.Extension:
        """Return capabilities for ``AL_EXT_MULAW``."""

        return self._get('AL_EXT_MULAW')

    @property
    def al_ext_alaw(self) -> _extensions.Extension:
        """Return capabilities for ``AL_EXT_ALAW``."""

        return self._get('AL_EXT_ALAW')

    @property
    def alc_loki_audio_channel(self) -> _extensions.Extension:
        """Return capabilities for ``ALC_LOKI_audio_channel``."""

        return self._get('ALC_LOKI_audio_channel')

    @property
    def al_ext_mcformats(self) -> _extensions.Extension:
        """Return capabilities for ``AL_EXT_MCFORMATS``."""

        return self._get('AL_EXT_MCFORMATS')

    @property
    def al_ext_mulaw_mcformats(self) -> _extensions.Extension:
        """Return capabilities for ``AL_EXT_MULAW_MCFORMATS``."""

        return self._get('AL_EXT_MULAW_MCFORMATS')

    @property
    def al_ext_ima4(self) -> _extensions.Extension:
        """Return capabilities for ``AL_EXT_IMA4``."""

        return self._get('AL_EXT_IMA4')

    @property
    def al_ext_static_buffer(self) -> _extensions.Extension:
        """Return capabilities for ``AL_EXT_STATIC_BUFFER``."""

        return self._get('AL_EXT_STATIC_BUFFER')

    @property
    def alc_ext_efx(self) -> _extensions.Extension:
        """Return capabilities for ``ALC_EXT_EFX``."""

        return self._get('ALC_EXT_EFX')

    @property
    def alc_ext_disconnect(self) -> _extensions.Extension:
        """Return capabilities for ``ALC_EXT_disconnect``."""

        return self._get('ALC_EXT_disconnect')

    @property
    def alc_ext_thread_local_context(self) -> _extensions.Extension:
        """Return capabilities for ``ALC_EXT_thread_local_context``."""

        return self._get('ALC_EXT_thread_local_context')

    @property
    def al_ext_source_distance_model(self) -> _extensions.Extension:
        """Return capabilities for ``AL_EXT_source_distance_model``."""

        return self._get('AL_EXT_source_distance_model')

    @property
    def al_soft_buffer_sub_data(self) -> _extensions.Extension:
        """Return capabilities for ``AL_SOFT_buffer_sub_data``."""

        return self._get('AL_SOFT_buffer_sub_data')

    @property
    def al_soft_loop_points(self) -> _extensions.Extension:
        """Return capabilities for ``AL_SOFT_loop_points``."""

        return self._get('AL_SOFT_loop_points')

    @property
    def al_ext_foldback(self) -> _extensions.Extension:
        """Return capabilities for ``AL_EXT_FOLDBACK``."""

        return self._get('AL_EXT_FOLDBACK')

    @property
    def alc_ext_dedicated(self) -> _extensions.Extension:
        """Return capabilities for ``ALC_EXT_DEDICATED``."""

        return self._get('ALC_EXT_DEDICATED')

    @property
    def al_soft_buffer_samples(self) -> _extensions.Extension:
        """Return capabilities for ``AL_SOFT_buffer_samples``."""

        return self._get('AL_SOFT_buffer_samples')

    @property
    def al_soft_direct_channels(self) -> _extensions.Extension:
        """Return capabilities for ``AL_SOFT_direct_channels``."""

        return self._get('AL_SOFT_direct_channels')

    @property
    def alc_soft_loopback(self) -> _extensions.Extension:
        """Return capabilities for ``ALC_SOFT_loopback``."""

        return self._get('ALC_SOFT_loopback')

    @property
    def al_ext_stereo_angles(self) -> _extensions.Extension:
        """Return capabilities for ``AL_EXT_STEREO_ANGLES``."""

        return self._get('AL_EXT_STEREO_ANGLES')

    @property
    def al_ext_source_radius(self) -> _extensions.Extension:
        """Return capabilities for ``AL_EXT_SOURCE_RADIUS``."""

        return self._get('AL_EXT_SOURCE_RADIUS')

    @property
    def al_soft_source_latency(self) -> _extensions.Extension:
        """Return capabilities for ``AL_SOFT_source_latency``."""

        return self._get('AL_SOFT_source_latency')

    @property
    def alc_ext_default_filter_order(self) -> _extensions.Extension:
        """Return capabilities for ``ALC_EXT_DEFAULT_FILTER_ORDER``."""

        return self._get('ALC_EXT_DEFAULT_FILTER_ORDER')

    @property
    def al_soft_deferred_updates(self) -> _extensions.Extension:
        """Return capabilities for ``AL_SOFT_deferred_updates``."""

        return self._get('AL_SOFT_deferred_updates')

    @property
    def al_soft_block_alignment(self) -> _extensions.Extension:
        """Return capabilities for ``AL_SOFT_block_alignment``."""

        return self._get('AL_SOFT_block_alignment')

    @property
    def al_soft_msadpcm(self) -> _extensions.Extension:
        """Return capabilities for ``AL_SOFT_MSADPCM``."""

        return self._get('AL_SOFT_MSADPCM')

    @property
    def al_soft_source_length(self) -> _extensions.Extension:
        """Return capabilities for ``AL_SOFT_source_length``."""

        return self._get('AL_SOFT_source_length')

    @property
    def al_soft_buffer_length_query(self) -> _extensions.Extension:
        """Return capabilities for ``AL_SOFT_buffer_length_query``."""

        return self._get('AL_SOFT_buffer_length_query')

    @property
    def alc_soft_pause_device(self) -> _extensions.Extension:
        """Return capabilities for ``ALC_SOFT_pause_device``."""

        return self._get('ALC_SOFT_pause_device')

    @property
    def al_ext_bformat(self) -> _extensions.Extension:
        """Return capabilities for ``AL_EXT_BFORMAT``."""

        return self._get('AL_EXT_BFORMAT')

    @property
    def al_ext_mulaw_bformat(self) -> _extensions.Extension:
        """Return capabilities for ``AL_EXT_MULAW_BFORMAT``."""

        return self._get('AL_EXT_MULAW_BFORMAT')

    @property
    def alc_soft_hrtf(self) -> _extensions.Extension:
        """Return capabilities for ``ALC_SOFT_HRTF``."""

        return self._get('ALC_SOFT_HRTF')

    @property
    def al_soft_gain_clamp_ex(self) -> _extensions.Extension:
        """Return capabilities for ``AL_SOFT_gain_clamp_ex``."""

        return self._get('AL_SOFT_gain_clamp_ex')

    @property
    def al_soft_source_resampler(self) -> _extensions.Extension:
        """Return capabilities for ``AL_SOFT_source_resampler``."""

        return self._get('AL_SOFT_source_resampler')

    @property
    def al_soft_source_spatialize(self) -> _extensions.Extension:
        """Return capabilities for ``AL_SOFT_source_spatialize``."""

        return self._get('AL_SOFT_source_spatialize')

    @property
    def alc_soft_output_limiter(self) -> _extensions.Extension:
        """Return capabilities for ``ALC_SOFT_output_limiter``."""

        return self._get('ALC_SOFT_output_limiter')

    @property
    def alc_soft_device_clock(self) -> _extensions.Extension:
        """Return capabilities for ``ALC_SOFT_device_clock``."""

        return self._get('ALC_SOFT_device_clock')

    @property
    def al_soft_direct_channels_remix(self) -> _extensions.Extension:
        """Return capabilities for ``AL_SOFT_direct_channels_remix``."""

        return self._get('AL_SOFT_direct_channels_remix')

    @property
    def al_soft_bformat_ex(self) -> _extensions.Extension:
        """Return capabilities for ``AL_SOFT_bformat_ex``."""

        return self._get('AL_SOFT_bformat_ex')

    @property
    def alc_soft_loopback_bformat(self) -> _extensions.Extension:
        """Return capabilities for ``ALC_SOFT_loopback_bformat``."""

        return self._get('ALC_SOFT_loopback_bformat')

    @property
    def al_soft_effect_target(self) -> _extensions.Extension:
        """Return capabilities for ``AL_SOFT_effect_target``."""

        return self._get('AL_SOFT_effect_target')

    @property
    def al_soft_events(self) -> _extensions.Extension:
        """Return capabilities for ``AL_SOFT_events``."""

        return self._get('AL_SOFT_events')

    @property
    def alc_soft_reopen_device(self) -> _extensions.Extension:
        """Return capabilities for ``ALC_SOFT_reopen_device``."""

        return self._get('ALC_SOFT_reopen_device')

    @property
    def al_soft_callback_buffer(self) -> _extensions.Extension:
        """Return capabilities for ``AL_SOFT_callback_buffer``."""

        return self._get('AL_SOFT_callback_buffer')

    @property
    def al_soft_uhj(self) -> _extensions.Extension:
        """Return capabilities for ``AL_SOFT_UHJ``."""

        return self._get('AL_SOFT_UHJ')

    @property
    def al_soft_uhj_ex(self) -> _extensions.Extension:
        """Return capabilities for ``AL_SOFT_UHJ_ex``."""

        return self._get('AL_SOFT_UHJ_ex')

    @property
    def alc_soft_output_mode(self) -> _extensions.Extension:
        """Return capabilities for ``ALC_SOFT_output_mode``."""

        return self._get('ALC_SOFT_output_mode')

    @property
    def al_soft_source_start_delay(self) -> _extensions.Extension:
        """Return capabilities for ``AL_SOFT_source_start_delay``."""

        return self._get('AL_SOFT_source_start_delay')

    @property
    def alc_ext_debug(self) -> _extensions.Extension:
        """Return capabilities for ``ALC_EXT_debug``."""

        return self._get('ALC_EXT_debug')

    @property
    def al_ext_debug(self) -> _extensions.Extension:
        """Return capabilities for ``AL_EXT_debug``."""

        return self._get('AL_EXT_debug')

    @property
    def alc_soft_system_events(self) -> _extensions.Extension:
        """Return capabilities for ``ALC_SOFT_system_events``."""

        return self._get('ALC_SOFT_system_events')

    @property
    def al_ext_direct_context(self) -> _extensions.Extension:
        """Return capabilities for ``AL_EXT_direct_context``."""

        return self._get('AL_EXT_direct_context')

    @property
    def al_soft_bformat_hoa(self) -> _extensions.Extension:
        """Return capabilities for ``AL_SOFT_bformat_hoa``."""

        return self._get('AL_SOFT_bformat_hoa')

__all__ = ('ExtensionCapabilities',)
