# Generated by tools/generate_bindings.py. Do not edit by hand.
# OpenAL Soft 1.25.2: b2c48f7718ef3fcf67921a8b6534c4914e328970
# Source: https://raw.githubusercontent.com/kcat/openal-soft/1.25.2/registry/xml/al.xml
# Registry SHA-256: f4a5eb2f94adbb80e8afb1c510d2993932eb74519568c28f3e4919864acddf4a
# Registry notice: LICENSES/OpenAL-Registry.txt

from __future__ import annotations

from pyalsoft.bindings import _objects
from pyalsoft.bindings._generated import enums as _enums

class Buffer(_objects.ALObject):
    """Typed handle for an OpenAL buffer."""

    object_name = 'buffer'

    frequency: _objects.ALProperty[int] = (
        _objects.ALProperty('buffer', 'AL_FREQUENCY')
    )

    bits: _objects.ALProperty[int] = (
        _objects.ALProperty('buffer', 'AL_BITS')
    )

    channels: _objects.ALProperty[int] = (
        _objects.ALProperty('buffer', 'AL_CHANNELS')
    )

    size: _objects.ALProperty[int] = (
        _objects.ALProperty('buffer', 'AL_SIZE')
    )

    loop_points_soft: _objects.ALProperty[tuple[int, int]] = (
        _objects.ALProperty('buffer', 'AL_LOOP_POINTS_SOFT')
    )

    internal_format_soft: _objects.ALProperty[_enums.ALInternalFormatSOFT] = (
        _objects.ALProperty('buffer', 'AL_INTERNAL_FORMAT_SOFT')
    )

    byte_length_soft: _objects.ALProperty[int] = (
        _objects.ALProperty('buffer', 'AL_BYTE_LENGTH_SOFT')
    )

    sample_length_soft: _objects.ALProperty[int] = (
        _objects.ALProperty('buffer', 'AL_SAMPLE_LENGTH_SOFT')
    )

    sec_length_soft: _objects.ALProperty[float] = (
        _objects.ALProperty('buffer', 'AL_SEC_LENGTH_SOFT')
    )

    unpack_block_alignment_soft: _objects.ALProperty[int] = (
        _objects.ALProperty('buffer', 'AL_UNPACK_BLOCK_ALIGNMENT_SOFT')
    )

    pack_block_alignment_soft: _objects.ALProperty[int] = (
        _objects.ALProperty('buffer', 'AL_PACK_BLOCK_ALIGNMENT_SOFT')
    )

    ambisonic_layout_soft: _objects.ALProperty[_enums.ALAmbisonicLayoutSOFT] = (
        _objects.ALProperty('buffer', 'AL_AMBISONIC_LAYOUT_SOFT')
    )

    ambisonic_scaling_soft: _objects.ALProperty[_enums.ALAmbisonicScalingSOFT] = (
        _objects.ALProperty('buffer', 'AL_AMBISONIC_SCALING_SOFT')
    )

    unpack_ambisonic_order_soft: _objects.ALProperty[int] = (
        _objects.ALProperty('buffer', 'AL_UNPACK_AMBISONIC_ORDER_SOFT')
    )

class Effect(_objects.ALObject):
    """Typed handle for an OpenAL effect."""

    object_name = 'effect'

    reverb_density: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_REVERB_DENSITY')
    )

    reverb_diffusion: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_REVERB_DIFFUSION')
    )

    reverb_gain: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_REVERB_GAIN')
    )

    reverb_gainhf: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_REVERB_GAINHF')
    )

    reverb_decay_time: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_REVERB_DECAY_TIME')
    )

    reverb_decay_hfratio: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_REVERB_DECAY_HFRATIO')
    )

    reverb_reflections_gain: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_REVERB_REFLECTIONS_GAIN')
    )

    reverb_reflections_delay: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_REVERB_REFLECTIONS_DELAY')
    )

    reverb_late_reverb_gain: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_REVERB_LATE_REVERB_GAIN')
    )

    reverb_late_reverb_delay: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_REVERB_LATE_REVERB_DELAY')
    )

    reverb_air_absorption_gainhf: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_REVERB_AIR_ABSORPTION_GAINHF')
    )

    reverb_room_rolloff_factor: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_REVERB_ROOM_ROLLOFF_FACTOR')
    )

    reverb_decay_hflimit: _objects.ALProperty[bool] = (
        _objects.ALProperty('effect', 'AL_REVERB_DECAY_HFLIMIT')
    )

    eaxreverb_density: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_EAXREVERB_DENSITY')
    )

    eaxreverb_diffusion: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_EAXREVERB_DIFFUSION')
    )

    eaxreverb_gain: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_EAXREVERB_GAIN')
    )

    eaxreverb_gainhf: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_EAXREVERB_GAINHF')
    )

    eaxreverb_gainlf: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_EAXREVERB_GAINLF')
    )

    eaxreverb_decay_time: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_EAXREVERB_DECAY_TIME')
    )

    eaxreverb_decay_hfratio: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_EAXREVERB_DECAY_HFRATIO')
    )

    eaxreverb_decay_lfratio: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_EAXREVERB_DECAY_LFRATIO')
    )

    eaxreverb_reflections_gain: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_EAXREVERB_REFLECTIONS_GAIN')
    )

    eaxreverb_reflections_delay: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_EAXREVERB_REFLECTIONS_DELAY')
    )

    eaxreverb_reflections_pan: _objects.ALProperty[tuple[float, float, float]] = (
        _objects.ALProperty('effect', 'AL_EAXREVERB_REFLECTIONS_PAN')
    )

    eaxreverb_late_reverb_gain: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_EAXREVERB_LATE_REVERB_GAIN')
    )

    eaxreverb_late_reverb_delay: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_EAXREVERB_LATE_REVERB_DELAY')
    )

    eaxreverb_late_reverb_pan: _objects.ALProperty[tuple[float, float, float]] = (
        _objects.ALProperty('effect', 'AL_EAXREVERB_LATE_REVERB_PAN')
    )

    eaxreverb_echo_time: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_EAXREVERB_ECHO_TIME')
    )

    eaxreverb_echo_depth: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_EAXREVERB_ECHO_DEPTH')
    )

    eaxreverb_modulation_time: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_EAXREVERB_MODULATION_TIME')
    )

    eaxreverb_modulation_depth: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_EAXREVERB_MODULATION_DEPTH')
    )

    eaxreverb_air_absorption_gainhf: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_EAXREVERB_AIR_ABSORPTION_GAINHF')
    )

    eaxreverb_hfreference: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_EAXREVERB_HFREFERENCE')
    )

    eaxreverb_lfreference: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_EAXREVERB_LFREFERENCE')
    )

    eaxreverb_room_rolloff_factor: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_EAXREVERB_ROOM_ROLLOFF_FACTOR')
    )

    eaxreverb_decay_hflimit: _objects.ALProperty[bool] = (
        _objects.ALProperty('effect', 'AL_EAXREVERB_DECAY_HFLIMIT')
    )

    chorus_waveform: _objects.ALProperty[_enums.ALChorusWaveform] = (
        _objects.ALProperty('effect', 'AL_CHORUS_WAVEFORM')
    )

    chorus_phase: _objects.ALProperty[int] = (
        _objects.ALProperty('effect', 'AL_CHORUS_PHASE')
    )

    chorus_rate: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_CHORUS_RATE')
    )

    chorus_depth: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_CHORUS_DEPTH')
    )

    chorus_feedback: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_CHORUS_FEEDBACK')
    )

    chorus_delay: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_CHORUS_DELAY')
    )

    distortion_edge: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_DISTORTION_EDGE')
    )

    distortion_gain: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_DISTORTION_GAIN')
    )

    distortion_lowpass_cutoff: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_DISTORTION_LOWPASS_CUTOFF')
    )

    distortion_eqcenter: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_DISTORTION_EQCENTER')
    )

    distortion_eqbandwidth: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_DISTORTION_EQBANDWIDTH')
    )

    echo_delay: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_ECHO_DELAY')
    )

    echo_lrdelay: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_ECHO_LRDELAY')
    )

    echo_damping: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_ECHO_DAMPING')
    )

    echo_feedback: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_ECHO_FEEDBACK')
    )

    echo_spread: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_ECHO_SPREAD')
    )

    flanger_waveform: _objects.ALProperty[_enums.ALFlangerWaveform] = (
        _objects.ALProperty('effect', 'AL_FLANGER_WAVEFORM')
    )

    flanger_phase: _objects.ALProperty[int] = (
        _objects.ALProperty('effect', 'AL_FLANGER_PHASE')
    )

    flanger_rate: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_FLANGER_RATE')
    )

    flanger_depth: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_FLANGER_DEPTH')
    )

    flanger_feedback: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_FLANGER_FEEDBACK')
    )

    flanger_delay: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_FLANGER_DELAY')
    )

    frequency_shifter_frequency: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_FREQUENCY_SHIFTER_FREQUENCY')
    )

    frequency_shifter_left_direction: _objects.ALProperty[_enums.ALFrequencyShifterDirection] = (
        _objects.ALProperty('effect', 'AL_FREQUENCY_SHIFTER_LEFT_DIRECTION')
    )

    frequency_shifter_right_direction: _objects.ALProperty[_enums.ALFrequencyShifterDirection] = (
        _objects.ALProperty('effect', 'AL_FREQUENCY_SHIFTER_RIGHT_DIRECTION')
    )

    vocal_morpher_phonemea: _objects.ALProperty[_enums.ALVocalMorpherPhoneme] = (
        _objects.ALProperty('effect', 'AL_VOCAL_MORPHER_PHONEMEA')
    )

    vocal_morpher_phonemea_coarse_tuning: _objects.ALProperty[int] = (
        _objects.ALProperty('effect', 'AL_VOCAL_MORPHER_PHONEMEA_COARSE_TUNING')
    )

    vocal_morpher_phonemeb: _objects.ALProperty[_enums.ALVocalMorpherPhoneme] = (
        _objects.ALProperty('effect', 'AL_VOCAL_MORPHER_PHONEMEB')
    )

    vocal_morpher_phonemeb_coarse_tuning: _objects.ALProperty[int] = (
        _objects.ALProperty('effect', 'AL_VOCAL_MORPHER_PHONEMEB_COARSE_TUNING')
    )

    vocal_morpher_waveform: _objects.ALProperty[_enums.ALVocalMorpherWaveform] = (
        _objects.ALProperty('effect', 'AL_VOCAL_MORPHER_WAVEFORM')
    )

    vocal_morpher_rate: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_VOCAL_MORPHER_RATE')
    )

    pitch_shifter_coarse_tune: _objects.ALProperty[int] = (
        _objects.ALProperty('effect', 'AL_PITCH_SHIFTER_COARSE_TUNE')
    )

    pitch_shifter_fine_tune: _objects.ALProperty[int] = (
        _objects.ALProperty('effect', 'AL_PITCH_SHIFTER_FINE_TUNE')
    )

    ring_modulator_frequency: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_RING_MODULATOR_FREQUENCY')
    )

    ring_modulator_highpass_cutoff: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_RING_MODULATOR_HIGHPASS_CUTOFF')
    )

    ring_modulator_waveform: _objects.ALProperty[_enums.ALRingModulatorWaveform] = (
        _objects.ALProperty('effect', 'AL_RING_MODULATOR_WAVEFORM')
    )

    autowah_attack_time: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_AUTOWAH_ATTACK_TIME')
    )

    autowah_release_time: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_AUTOWAH_RELEASE_TIME')
    )

    autowah_resonance: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_AUTOWAH_RESONANCE')
    )

    autowah_peak_gain: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_AUTOWAH_PEAK_GAIN')
    )

    compressor_onoff: _objects.ALProperty[bool] = (
        _objects.ALProperty('effect', 'AL_COMPRESSOR_ONOFF')
    )

    equalizer_low_gain: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_EQUALIZER_LOW_GAIN')
    )

    equalizer_low_cutoff: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_EQUALIZER_LOW_CUTOFF')
    )

    equalizer_mid1_gain: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_EQUALIZER_MID1_GAIN')
    )

    equalizer_mid1_center: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_EQUALIZER_MID1_CENTER')
    )

    equalizer_mid1_width: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_EQUALIZER_MID1_WIDTH')
    )

    equalizer_mid2_gain: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_EQUALIZER_MID2_GAIN')
    )

    equalizer_mid2_center: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_EQUALIZER_MID2_CENTER')
    )

    equalizer_mid2_width: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_EQUALIZER_MID2_WIDTH')
    )

    equalizer_high_gain: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_EQUALIZER_HIGH_GAIN')
    )

    equalizer_high_cutoff: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_EQUALIZER_HIGH_CUTOFF')
    )

    type: _objects.ALProperty[_enums.ALEffectType] = (
        _objects.ALProperty('effect', 'AL_EFFECT_TYPE')
    )

    dedicated_gain: _objects.ALProperty[float] = (
        _objects.ALProperty('effect', 'AL_DEDICATED_GAIN')
    )

class Filter(_objects.ALObject):
    """Typed handle for an OpenAL filter."""

    object_name = 'filter'

    lowpass_gain: _objects.ALProperty[float] = (
        _objects.ALProperty('filter', 'AL_LOWPASS_GAIN')
    )

    lowpass_gainhf: _objects.ALProperty[float] = (
        _objects.ALProperty('filter', 'AL_LOWPASS_GAINHF')
    )

    highpass_gain: _objects.ALProperty[float] = (
        _objects.ALProperty('filter', 'AL_HIGHPASS_GAIN')
    )

    highpass_gainlf: _objects.ALProperty[float] = (
        _objects.ALProperty('filter', 'AL_HIGHPASS_GAINLF')
    )

    bandpass_gain: _objects.ALProperty[float] = (
        _objects.ALProperty('filter', 'AL_BANDPASS_GAIN')
    )

    bandpass_gainlf: _objects.ALProperty[float] = (
        _objects.ALProperty('filter', 'AL_BANDPASS_GAINLF')
    )

    bandpass_gainhf: _objects.ALProperty[float] = (
        _objects.ALProperty('filter', 'AL_BANDPASS_GAINHF')
    )

    type: _objects.ALProperty[_enums.ALFilterType] = (
        _objects.ALProperty('filter', 'AL_FILTER_TYPE')
    )

class AuxiliaryEffectSlot(_objects.ALObject):
    """Typed handle for an OpenAL auxiliary effect slot."""

    object_name = 'auxiliary effect slot'

    effect: _objects.ALProperty[Effect | None] = (
        _objects.ALProperty('auxiliary effect slot', 'AL_EFFECTSLOT_EFFECT')
    )

    gain: _objects.ALProperty[float] = (
        _objects.ALProperty('auxiliary effect slot', 'AL_EFFECTSLOT_GAIN')
    )

    auxiliary_send_auto: _objects.ALProperty[bool] = (
        _objects.ALProperty('auxiliary effect slot', 'AL_EFFECTSLOT_AUXILIARY_SEND_AUTO')
    )

    target_soft: _objects.ALProperty[AuxiliaryEffectSlot | None] = (
        _objects.ALProperty('auxiliary effect slot', 'AL_EFFECTSLOT_TARGET_SOFT')
    )

class Source(_objects.ALObject):
    """Typed handle for an OpenAL source."""

    object_name = 'source'

    relative: _objects.ALProperty[bool] = (
        _objects.ALProperty('source', 'AL_SOURCE_RELATIVE')
    )

    cone_inner_angle: _objects.ALProperty[float] = (
        _objects.ALProperty('source', 'AL_CONE_INNER_ANGLE')
    )

    cone_outer_angle: _objects.ALProperty[float] = (
        _objects.ALProperty('source', 'AL_CONE_OUTER_ANGLE')
    )

    pitch: _objects.ALProperty[float] = (
        _objects.ALProperty('source', 'AL_PITCH')
    )

    position: _objects.ALProperty[tuple[float, float, float]] = (
        _objects.ALProperty('source', 'AL_POSITION')
    )

    direction: _objects.ALProperty[tuple[float, float, float]] = (
        _objects.ALProperty('source', 'AL_DIRECTION')
    )

    velocity: _objects.ALProperty[tuple[float, float, float]] = (
        _objects.ALProperty('source', 'AL_VELOCITY')
    )

    looping: _objects.ALProperty[bool] = (
        _objects.ALProperty('source', 'AL_LOOPING')
    )

    buffer: _objects.ALProperty[Buffer | None] = (
        _objects.ALProperty('source', 'AL_BUFFER')
    )

    gain: _objects.ALProperty[float] = (
        _objects.ALProperty('source', 'AL_GAIN')
    )

    min_gain: _objects.ALProperty[float] = (
        _objects.ALProperty('source', 'AL_MIN_GAIN')
    )

    max_gain: _objects.ALProperty[float] = (
        _objects.ALProperty('source', 'AL_MAX_GAIN')
    )

    state: _objects.ALProperty[_enums.ALSourceState] = (
        _objects.ALProperty('source', 'AL_SOURCE_STATE')
    )

    buffers_queued: _objects.ALProperty[int] = (
        _objects.ALProperty('source', 'AL_BUFFERS_QUEUED')
    )

    buffers_processed: _objects.ALProperty[int] = (
        _objects.ALProperty('source', 'AL_BUFFERS_PROCESSED')
    )

    reference_distance: _objects.ALProperty[float] = (
        _objects.ALProperty('source', 'AL_REFERENCE_DISTANCE')
    )

    rolloff_factor: _objects.ALProperty[float] = (
        _objects.ALProperty('source', 'AL_ROLLOFF_FACTOR')
    )

    cone_outer_gain: _objects.ALProperty[float] = (
        _objects.ALProperty('source', 'AL_CONE_OUTER_GAIN')
    )

    max_distance: _objects.ALProperty[float] = (
        _objects.ALProperty('source', 'AL_MAX_DISTANCE')
    )

    sec_offset: _objects.ALProperty[float] = (
        _objects.ALProperty('source', 'AL_SEC_OFFSET')
    )

    sample_offset: _objects.ALProperty[int] = (
        _objects.ALProperty('source', 'AL_SAMPLE_OFFSET')
    )

    byte_offset: _objects.ALProperty[int] = (
        _objects.ALProperty('source', 'AL_BYTE_OFFSET')
    )

    type: _objects.ALProperty[_enums.ALSourceType] = (
        _objects.ALProperty('source', 'AL_SOURCE_TYPE')
    )

    direct_filter: _objects.ALProperty[Filter | None] = (
        _objects.ALProperty('source', 'AL_DIRECT_FILTER')
    )

    air_absorption_factor: _objects.ALProperty[float] = (
        _objects.ALProperty('source', 'AL_AIR_ABSORPTION_FACTOR')
    )

    room_rolloff_factor: _objects.ALProperty[float] = (
        _objects.ALProperty('source', 'AL_ROOM_ROLLOFF_FACTOR')
    )

    cone_outer_gainhf: _objects.ALProperty[float] = (
        _objects.ALProperty('source', 'AL_CONE_OUTER_GAINHF')
    )

    direct_filter_gainhf_auto: _objects.ALProperty[bool] = (
        _objects.ALProperty('source', 'AL_DIRECT_FILTER_GAINHF_AUTO')
    )

    auxiliary_send_filter_gain_auto: _objects.ALProperty[bool] = (
        _objects.ALProperty('source', 'AL_AUXILIARY_SEND_FILTER_GAIN_AUTO')
    )

    auxiliary_send_filter_gainhf_auto: _objects.ALProperty[bool] = (
        _objects.ALProperty('source', 'AL_AUXILIARY_SEND_FILTER_GAINHF_AUTO')
    )

    byte_rw_offsets_soft: _objects.ALProperty[tuple[float, float]] = (
        _objects.ALProperty('source', 'AL_BYTE_RW_OFFSETS_SOFT')
    )

    sample_rw_offsets_soft: _objects.ALProperty[tuple[float, float]] = (
        _objects.ALProperty('source', 'AL_SAMPLE_RW_OFFSETS_SOFT')
    )

    direct_channels_soft: _objects.ALProperty[_enums.ALDirectChannelsSOFT] = (
        _objects.ALProperty('source', 'AL_DIRECT_CHANNELS_SOFT')
    )

    stereo_angles: _objects.ALProperty[tuple[float, float]] = (
        _objects.ALProperty('source', 'AL_STEREO_ANGLES')
    )

    radius: _objects.ALProperty[float] = (
        _objects.ALProperty('source', 'AL_SOURCE_RADIUS')
    )

    sample_offset_latency_soft: _objects.ALProperty[tuple[int, int]] = (
        _objects.ALProperty('source', 'AL_SAMPLE_OFFSET_LATENCY_SOFT')
    )

    sec_offset_latency_soft: _objects.ALProperty[tuple[float, float]] = (
        _objects.ALProperty('source', 'AL_SEC_OFFSET_LATENCY_SOFT')
    )

    resampler_soft: _objects.ALProperty[int] = (
        _objects.ALProperty('source', 'AL_SOURCE_RESAMPLER_SOFT')
    )

    spatialize_soft: _objects.ALProperty[_enums.ALSourceSpatializeSOFT] = (
        _objects.ALProperty('source', 'AL_SOURCE_SPATIALIZE_SOFT')
    )

    sample_offset_clock_soft: _objects.ALProperty[int] = (
        _objects.ALProperty('source', 'AL_SAMPLE_OFFSET_CLOCK_SOFT')
    )

    sec_offset_clock_soft: _objects.ALProperty[float] = (
        _objects.ALProperty('source', 'AL_SEC_OFFSET_CLOCK_SOFT')
    )

    stereo_mode_soft: _objects.ALProperty[_enums.ALStereoModeSOFT] = (
        _objects.ALProperty('source', 'AL_STEREO_MODE_SOFT')
    )

    super_stereo_width_soft: _objects.ALProperty[float] = (
        _objects.ALProperty('source', 'AL_SUPER_STEREO_WIDTH_SOFT')
    )

class Listener(_objects.ALSingletonObject):
    """Typed handle for an OpenAL listener."""

    object_name = 'listener'

    position: _objects.ALProperty[tuple[float, float, float]] = (
        _objects.ALProperty('listener', 'AL_POSITION')
    )

    velocity: _objects.ALProperty[tuple[float, float, float]] = (
        _objects.ALProperty('listener', 'AL_VELOCITY')
    )

    gain: _objects.ALProperty[float] = (
        _objects.ALProperty('listener', 'AL_GAIN')
    )

    orientation: _objects.ALProperty[tuple[float, float, float, float, float, float]] = (
        _objects.ALProperty('listener', 'AL_ORIENTATION')
    )

    meters_per_unit: _objects.ALProperty[float] = (
        _objects.ALProperty('listener', 'AL_METERS_PER_UNIT')
    )

__all__ = (
    'Buffer',
    'Effect',
    'Filter',
    'AuxiliaryEffectSlot',
    'Source',
    'Listener',
)
